# Generated by Django 5.0.1 on 2024-01-26 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_productrecipe_product_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productrecipe",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="productrecipe",
            unique_together={("product", "recipe")},
        ),
    ]
